language: node_js
node_js:
  - 12.7.0
branches:
  only:
    - master
addons:
  ssh_known_hosts: tehwol.fi:3695
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - ng test
  - ng build --prod --aot --build-optimizer
  - npm run scully
before_deploy:
  - wget http://de.archive.ubuntu.com/ubuntu/pool/universe/s/sshpass/sshpass_1.06-1_amd64.deb
  - sudo dpkg -i sshpass_1.06-1_amd64.deb
  - openssl aes-256-cbc -K $encrypted_ed1737b0524d_key -iv $encrypted_ed1737b0524d_iv
    -in deploy_key.enc -out deploy_key -d
  - openssl aes-256-cbc -K $encrypted_b2acfa2de9eb_key -iv $encrypted_b2acfa2de9eb_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - chmod 0600 deploy_*
deploy:
  provider: script
  skip_cleanup: true
  script: sshpass -f deploy_key -P 'Enter passphrase' ssh -i deploy_rsa -p 3695 -o StrictHostKeyChecking=no tehwolfi@tehwol.fi "find /home/tehwolfi/public_html/ -type f -name \"[^.]*\" -delete" && sshpass -f deploy_key -P 'Enter passphrase' scp -i deploy_rsa -P 3695 -o StrictHostKeyChecking=no -rp $TRAVIS_BUILD_DIR/dist/static/* tehwolfi@tehwol.fi:/home/tehwolfi/public_html/
  on:
    branch: master
