name: tehw0lf build frontend and portfolio library

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.4.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm@6
      - name: Install packages
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm affected:lint --parallel -- --base=$(git rev-parse HEAD~1)
      - name: Test
        run: pnpm affected:test --parallel -- --base=$(git rev-parse HEAD~1)
      #- name: Run end to end tests # works locally, but not on ci
      #run: pnpm affected:e2e -- --base=$(git rev-parse HEAD~1)
      - name: Build
        run: pnpm affected:build -- --base=$(git rev-parse HEAD~1)
      - name: Run scully
        run: pnpm run scully
      - name: Compress (gzip)
        run: pnpm run compress
      - name: Publish library to npm registry
        run: |
          npm publish --access public --dry-run
          npm publich --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Prepare frontend deployment
        run: |
          openssl aes-256-cbc -K $DEPLOY_KEY -iv $DEPLOY_KEY_IV -in deploy_key.enc -out deploy_key -d
          openssl aes-256-cbc -K $DEPLOY_RSA -iv $DEPLOY_RSA_IV -in deploy_rsa.enc -out deploy_rsa -d
          chmod 0600 deploy_*
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_KEY_IV: ${{ secrets.DEPLOY_KEY_IV }}
          DEPLOY_RSA: ${{ secrets.DEPLOY_RSA }}
          DEPLOY_RSA_IV: ${{ secrets.DEPLOY_RSA_IV }}
      - name: Prepare deploy
        uses: matheusvanzan/sshpass-action@v2
      - name: Deploy frontend
        run: |
          sshpass -f deploy_key -P 'Enter passphrase' ssh -i deploy_rsa -p $PORT -o StrictHostKeyChecking=no $USER@$HOST "find /home/$USER/public_html/ -type f -name \"[^.]*\" -delete" && sshpass -f deploy_key -P 'Enter passphrase' scp -i deploy_rsa -P $PORT -o StrictHostKeyChecking=no -rp $${{ github.workspace }}/dist/static/* $USER@$HOST:/home/$USER/public_html/
          rm deploy_*
        env:
          HOST: tehwol.fi
          PORT: 3695
          USER: tehwolfi
