name: weekly lighthouse scan

on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:

jobs:
  lighthouse:
    name: external workflow
    uses: tehw0lf/workflows/.github/workflows/lighthouse-scan.yml@main
    permissions:
      contents: read
      issues: write
    with:
      target_url: "https://tehwolf.de"
      min_performance: 70
      min_accessibility: 100
      min_best_practices: 95
      min_seo: 100
