name: Check for new NX version

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: npm ci
      - uses: timonmasberg/nx-migration-gh-action@v1.0.0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          prTitle: 'Migrate Nx to $VERSION'
